import { query } from '../pool.js';

const settings = [
  // Brand
  { key: 'brand.name', uz: 'SEVEN SCHOOL', ru: 'SEVEN SCHOOL', en: 'SEVEN SCHOOL', group: 'brand' },
  { key: 'brand.tagline', uz: 'EST. 2018 · TASHKENT', ru: 'EST. 2018 · TASHKENT', en: 'EST. 2018 · TASHKENT', group: 'brand' },
  { key: 'brand.description',
    uz: "Toshkentdagi yetakchi xususiy maktab — yoshlarimizni dunyo TOP universitetlariga olib boruvchi xavfsiz ko'prik.",
    ru: 'Ведущая частная школа Ташкента — безопасный мост, ведущий нашу молодёжь в TOP университеты мира.',
    en: 'Tashkent\'s leading private school — a safe bridge taking our youth to the world\'s top universities.',
    group: 'brand',
  },

  // Contact
  { key: 'contact.phone', raw: '+998 78 888 80 80', group: 'contact' },
  { key: 'contact.phone_link', raw: '+998788888080', group: 'contact' },
  { key: 'contact.address',
    uz: "Toshkent, Yunusobod tumani, Amir Temur ko'chasi 142",
    ru: 'Ташкент, Юнусабадский район, ул. Амира Темура 142',
    en: 'Tashkent, Yunusobod district, Amir Temur street 142',
    group: 'contact',
    description: "Bir nechta manzilni yangi qatordan yoki | belgisi bilan ajrating. Misol: \"Manzil 1 | Manzil 2\"",
  },
  { key: 'contact.hours',
    uz: 'Dushanba–Juma · 9:00–18:00',
    ru: 'Пн–Пт · 9:00–18:00',
    en: 'Mon–Fri · 9:00–18:00',
    group: 'contact',
  },
  { key: 'contact.telegram', raw: 'https://t.me/seven_schooluz', group: 'contact' },
  { key: 'contact.instagram', raw: 'https://instagram.com/sevenschool.uz', group: 'contact' },
  { key: 'contact.youtube', raw: 'https://youtube.com/@sevenschooluz', group: 'contact' },
  { key: 'contact.map_lat', raw: '', group: 'contact', description: 'Google Map latitude. Example: 41.3265' },
  { key: 'contact.map_lng', raw: '', group: 'contact', description: 'Google Map longitude. Example: 69.2848' },
  { key: 'contact.map_zoom', raw: '16', group: 'contact', description: 'Google Map zoom level. Usually 14-18.' },
  { key: 'contact.map_embed_url', raw: '', group: 'contact', description: 'Optional full Google Maps embed URL. If filled, it overrides lat/lng.' },

  // Hero (index)
  { key: 'hero.pill',
    uz: 'Qabul 2026–2027 ochiq · Joylar cheklangan',
    ru: 'Приём 2026–2027 открыт · Места ограничены',
    en: 'Admissions 2026–2027 open · Limited seats',
    group: 'hero',
  },
  { key: 'hero.title_main',
    uz: "Bizning o'quvchilar",
    ru: 'Наши ученики учатся в',
    en: 'Our students study at',
    group: 'hero',
  },
  { key: 'hero.title_accent',
    uz: 'Harvardda',
    ru: 'Гарварде',
    en: 'Harvard',
    group: 'hero',
  },
  { key: 'hero.title_suffix',
    uz: "o'qiydi",
    ru: '',
    en: '',
    group: 'hero',
  },
  { key: 'hero.lead',
    uz: "O'zbekistonda birinchi marta — Seven School o'quvchisi <strong>Harvardga kirdi</strong>. Bugun bizning o'quvchilar dunyoning <strong>TOP-100</strong> universitetlarida o'qishadi.",
    ru: 'Впервые в Узбекистане — ученик Seven School <strong>поступил в Гарвард</strong>. Сегодня наши ученики учатся в <strong>TOP-100</strong> университетах мира.',
    en: 'For the first time in Uzbekistan — a Seven School student <strong>got into Harvard</strong>. Today our students study at the world\'s <strong>TOP-100</strong> universities.',
    group: 'hero',
  },
  { key: 'hero.cta_primary',
    uz: 'Maslahat oling →',
    ru: 'Получить консультацию →',
    en: 'Get a consultation →',
    group: 'hero',
  },
  { key: 'hero.cta_secondary',
    uz: 'Natijalar bilan tanishing ↓',
    ru: 'Посмотреть результаты ↓',
    en: 'See our results ↓',
    group: 'hero',
  },

  // Hero stats
  { key: 'hero.stat_students_value', raw: '450', group: 'hero_stats' },
  { key: 'hero.stat_students_suffix', raw: '+', group: 'hero_stats' },
  { key: 'hero.stat_students_label', uz: "O'quvchi", ru: 'Учеников', en: 'Students', group: 'hero_stats' },
  { key: 'hero.stat_students_sub',
    uz: "Hozirda bizda ta'lim olishadi",
    ru: 'Сейчас учатся у нас',
    en: 'Currently studying with us',
    group: 'hero_stats',
  },
  // Medals stat
  { key: 'hero.stat_medals_value', raw: '29', group: 'hero_stats' },
  { key: 'hero.stat_medals_label', uz: 'Medal', ru: 'Медалей', en: 'Medals', group: 'hero_stats' },
  { key: 'hero.stat_medals_sub',
    uz: 'Birinchi yilda olimpiadalardan',
    ru: 'В первый год с олимпиад',
    en: 'From first-year olympiads',
    group: 'hero_stats',
  },
  // Sports stat
  { key: 'hero.stat_sports_value', raw: '4', group: 'hero_stats' },
  { key: 'hero.stat_sports_label', uz: 'Sport', ru: 'Спорт', en: 'Sports', group: 'hero_stats' },
  { key: 'hero.stat_sports_sub',
    uz: 'Suzish, taekvondo, gimnastika, tennis',
    ru: 'Плавание, тхэквондо, гимнастика, теннис',
    en: 'Swimming, taekwondo, gymnastics, tennis',
    group: 'hero_stats',
  },
  // AI stat
  { key: 'hero.stat_ai_value', uz: '5-sinf', ru: '5 класс', en: 'Grade 5', group: 'hero_stats' },
  { key: 'hero.stat_ai_label', uz: 'AI darslari', ru: 'Уроки ИИ', en: 'AI lessons', group: 'hero_stats' },
  { key: 'hero.stat_ai_sub',
    uz: '5–7-sinflar uchun',
    ru: 'Для 5–7 классов',
    en: 'For grades 5–7',
    group: 'hero_stats',
  },
  // Age stat
  { key: 'hero.stat_age_value', uz: '4 yosh', ru: 'С 4 лет', en: 'From age 4', group: 'hero_stats' },
  { key: 'hero.stat_age_label', uz: 'dan', ru: '', en: '', group: 'hero_stats' },
  { key: 'hero.stat_age_sub',
    uz: "Bog'chadan 7-sinfgacha",
    ru: 'От детсада до 7 класса',
    en: 'From preschool to grade 7',
    group: 'hero_stats',
  },

  // About home block
  { key: 'about_home.eyebrow', uz: 'Biz kimmiz?', ru: 'Кто мы?', en: 'Who we are', group: 'about_home' },
  { key: 'about_home.title',
    uz: 'Seven School — nima uchun eng yaxshi tanlov?',
    ru: 'Seven School — почему лучший выбор?',
    en: 'Seven School — why is it the best choice?',
    group: 'about_home',
  },
  { key: 'about_home.body',
    uz: "<p>Seven School — bu 7–11 sinfgacha bo'lgan o'quvchilarini dunyoning <strong>TOP universitetlariga</strong> kiritadigan xususiy maktab.</p><p>O'quvchilarga <strong>matematika, ingliz tili, tarix</strong> va bolaning shaxsiyati rivojlanishi uchun <strong>notiqlik san'ati</strong> va <strong>tanqidiy fikrlash</strong> darslari o'tiladi.</p><p>Dars beradigan ustozlar — <strong>8–25 yillik tajribaga ega</strong> mutaxassislar. Ular orasida ona tili, matematika va tarix darsliklarini yozgan <strong>muallif-o'qituvchilar</strong> bor.</p>",
    ru: '<p>Seven School — частная школа для учеников 7–11 классов, готовящая их к поступлению в <strong>топовые университеты мира</strong>.</p><p>Ученики изучают <strong>математику, английский, историю</strong>, а также <strong>ораторское искусство</strong> и <strong>критическое мышление</strong>.</p><p>Преподают опытные педагоги <strong>с опытом 8–25 лет</strong>, среди них — авторы школьных учебников.</p>',
    en: '<p>Seven School is a private school for grades 7–11 that prepares students for admission to the world\'s <strong>top universities</strong>.</p><p>Students learn <strong>math, English, history</strong>, plus <strong>public speaking</strong> and <strong>critical thinking</strong>.</p><p>Teachers have <strong>8–25 years of experience</strong> and include authors of national textbooks.</p>',
    group: 'about_home',
  },

  // Mission
  { key: 'mission.quote',
    uz: "Farzandingiz o'z tilini va qadriyatlarini yo'qotmasdan, dunyo bilan <span class=\"accent\">teng darajada raqobatlasha</span> oladigan bo'lib ulg'aysin.",
    ru: 'Пусть ваш ребёнок вырастет, не теряя родного языка и ценностей, и сможет <span class="accent">конкурировать на равных</span> с миром.',
    en: 'Let your child grow up keeping their language and values, and become able to <span class="accent">compete on equal terms</span> with the world.',
    group: 'mission',
  },
  { key: 'mission.subtitle',
    uz: "Biz bolani mustaqil fikrlashga va o'zi qaror qabul qilishga o'rgatamiz. Farzandingiz qayerda o'qisa ham, u hayotda o'z o'rnini topib ketadigan shaxs bo'lib chiqadi.",
    ru: 'Мы учим ребёнка мыслить самостоятельно и принимать решения. Где бы ваш ребёнок ни учился, он найдёт своё место в жизни.',
    en: 'We teach children to think independently and make their own decisions. Wherever your child studies, they will find their place in life.',
    group: 'mission',
  },
  { key: 'mission.label',
    uz: 'Bizning missiyamiz',
    ru: 'Наша миссия',
    en: 'Our mission',
    group: 'mission',
  },
  { key: 'mission.author',
    uz: 'Seven School jamoasi',
    ru: 'Команда Seven School',
    en: 'The Seven School team',
    group: 'mission',
  },
  { key: 'mission.title_brand',
    uz: 'Seven School', ru: 'Seven School', en: 'Seven School',
    group: 'mission',
  },
  { key: 'mission.title_accent',
    uz: 'maqsadi', ru: 'миссия', en: 'mission',
    group: 'mission',
  },

  // Pricing (new section on index)
  { key: 'pricing.eyebrow', uz: 'Narxlar', ru: 'Цены', en: 'Pricing', group: 'pricing' },
  { key: 'pricing.title',
    uz: "Oylik to'lov",
    ru: 'Ежемесячная оплата',
    en: 'Monthly tuition',
    group: 'pricing',
  },
  { key: 'pricing.label',
    uz: '7–11-sinflar uchun:',
    ru: 'Для 7–11 классов:',
    en: 'For grades 7–11:',
    group: 'pricing',
  },
  { key: 'pricing.amount', raw: '6 600 000', group: 'pricing' },
  { key: 'pricing.currency',
    uz: "so'm",
    ru: 'сум',
    en: 'soum',
    group: 'pricing',
  },
  { key: 'pricing.note',
    uz: '*Chegirmalar ham mavjud',
    ru: '*Доступны скидки',
    en: '*Discounts available',
    group: 'pricing',
  },
  { key: 'pricing.includes',
    uz: 'Barcha akademik fanlar|IELTS va SAT tayyorlov|Tarbiya fanlari|Universitetga hujjat topshirish yordami',
    ru: 'Все академические предметы|Подготовка к IELTS и SAT|Воспитательные предметы|Помощь в подаче документов в университеты',
    en: 'All academic subjects|IELTS and SAT preparation|Character subjects|University application assistance',
    group: 'pricing',
  },
  { key: 'pricing.cta',
    uz: 'Ariza topshirish →',
    ru: 'Подать заявку →',
    en: 'Apply →',
    group: 'pricing',
  },
  { key: 'home.pricing_eyebrow', uz: 'Narx', ru: 'Цена', en: 'Pricing', group: 'pricing' },
  { key: 'home.pricing_title',
    uz: "Narx — Shaffof narx. Yashirin to'lovlarsiz.",
    ru: 'Цена — прозрачная. Без скрытых платежей.',
    en: 'Transparent pricing. No hidden fees.',
    group: 'pricing',
  },
  { key: 'home.pricing_sub',
    uz: "Har bir narxga barcha mashg'ulotlar, ovqatlanish va to'garaklar kiradi.",
    ru: 'В каждую цену включены все занятия, питание и кружки.',
    en: 'Every price includes all classes, meals and clubs.',
    group: 'pricing',
  },
  { key: 'home.pricing_cta',
    uz: 'Sinov darsiga yozilish',
    ru: 'Записаться на пробный урок',
    en: 'Book a trial lesson',
    group: 'pricing',
  },

  // Clubs carousel (home)
  { key: 'home.togarak_eyebrow', uz: "To'garaklar bo'limi", ru: 'Кружки', en: 'Clubs', group: 'togaraklar' },
  { key: 'home.togarak_title',
    uz: "To'garaklar — qo'shimcha emas, dastur davomidir.",
    ru: 'Кружки — не дополнение, а часть программы.',
    en: "Clubs aren't an add-on — they're part of the program.",
    group: 'togaraklar',
  },
  { key: 'home.togarak_sub',
    uz: "Kulolchilik · Gimnastika · Suzish · Ijodkorlik · Rasm — hammasi bir joyda. Qo'shimcha qatnovsiz.",
    ru: 'Гончарное дело · Гимнастика · Плавание · Творчество · Рисование — всё в одном месте. Без поездок.',
    en: 'Pottery · Gymnastics · Swimming · Creativity · Drawing — all in one place. No extra trips.',
    group: 'togaraklar',
  },

  // Awards section (extra labels)
  { key: 'awards.subtitle',
    uz: "O'quvchilarimiz xalqaro musobaqalarda erishgan natijalari",
    ru: 'Результаты наших учеников на международных соревнованиях',
    en: "Our students' results at international competitions",
    group: 'awards',
  },
  { key: 'awards.summary_total_label',
    uz: 'Jami medallar',
    ru: 'Всего медалей',
    en: 'Total medals',
    group: 'awards',
  },
  { key: 'awards.summary_competitions_label',
    uz: 'Xalqaro musobaqa',
    ru: 'Международных конкурсов',
    en: 'International competitions',
    group: 'awards',
  },
  { key: 'awards.summary_winners_label',
    uz: "Sovrindor o'quvchi",
    ru: 'Учеников-призёров',
    en: 'Award-winning students',
    group: 'awards',
  },

  // Natijalar (results-dark) heading
  { key: 'results_dark.title',
    uz: "Natijalar o'zlari gapiradi",
    ru: 'Результаты говорят сами за себя',
    en: 'Results speak for themselves',
    group: 'results_dark',
  },
  { key: 'results_dark.subtitle',
    uz: 'IELTS, SAT natijalarimiz bilan tanishing',
    ru: 'Ознакомьтесь с нашими результатами IELTS и SAT',
    en: 'Take a look at our IELTS and SAT results',
    group: 'results_dark',
  },

  // Admissions section (index)
  { key: 'admissions.eyebrow', uz: 'Qabul 2026–2027', ru: 'Приём 2026–2027', en: 'Admissions 2026–2027', group: 'admissions' },
  { key: 'admissions.title',
    uz: 'Farzandingizni kelajak uchun hozirdan tayyorlang',
    ru: 'Готовьте ребёнка к будущему уже сегодня',
    en: "Prepare your child for the future today",
    group: 'admissions',
  },
  { key: 'admissions.desc',
    uz: "Qabul iyul oyida boshlanadi. Imtihondan yaxshi natija olgan o'quvchilarga ichki <strong>grant</strong> beriladi. Farzandingiz <strong>bepul</strong> yoki <strong>chegirma</strong> asosida o'qishi mumkin.",
    ru: 'Приём начинается в июле. Ученикам с высокими результатами вступительного экзамена предоставляется внутренний <strong>грант</strong>. Ваш ребёнок может учиться <strong>бесплатно</strong> или со <strong>скидкой</strong>.',
    en: 'Admissions start in July. Students with high entrance exam results receive an internal <strong>grant</strong>. Your child can study <strong>for free</strong> or with a <strong>discount</strong>.',
    group: 'admissions',
  },
  { key: 'admissions.scarcity',
    uz: "Joylar soni cheklangan — har sinfga atigi <strong>20 ta o'rin</strong>",
    ru: 'Места ограничены — всего <strong>20 мест</strong> на класс',
    en: 'Limited seats — only <strong>20 spots</strong> per grade',
    group: 'admissions',
  },

  // Admissions — column titles
  { key: 'admissions.process_title', uz: 'Qabul jarayoni', ru: 'Процесс приёма', en: 'Admission process', group: 'admissions' },
  { key: 'admissions.exams_title',  uz: 'Imtihon fanlari (2–7-sinf)', ru: 'Предметы экзамена (2–7 классы)', en: 'Exam subjects (grades 2–7)', group: 'admissions' },
  { key: 'admissions.info_title',   uz: "Ma'lumot", ru: 'Информация', en: 'Information', group: 'admissions' },

  // Admissions — exam test cards (3 fan)
  { key: 'admissions.test1_name', uz: 'Matematika',       ru: 'Математика',        en: 'Mathematics',       group: 'admissions' },
  { key: 'admissions.test1_sub',  uz: 'Mantiq va hisoblash', ru: 'Логика и счёт',   en: 'Logic and calculation', group: 'admissions' },
  { key: 'admissions.test2_name', uz: 'Mantiqiy fikrlash', ru: 'Логическое мышление', en: 'Logical thinking', group: 'admissions' },
  { key: 'admissions.test2_sub',  uz: 'Tahlil va mushohada', ru: 'Анализ и рассуждение', en: 'Analysis and reasoning', group: 'admissions' },
  { key: 'admissions.test3_name', uz: 'Ingliz tili',       ru: 'Английский',        en: 'English',           group: 'admissions' },
  { key: 'admissions.test3_sub',  uz: 'Grammar va reading', ru: 'Грамматика и чтение', en: 'Grammar and reading', group: 'admissions' },

  // Admissions — info card (4 rows)
  { key: 'admissions.info1_label', uz: 'Qabul yoshi',     ru: 'Возраст приёма',   en: 'Admission age',    group: 'admissions' },
  { key: 'admissions.info1_value', uz: '4 yoshdan 7-sinfgacha', ru: 'С 4 лет до 7 класса', en: 'From age 4 through grade 7', group: 'admissions' },
  { key: 'admissions.info2_label', uz: 'Har sinfda joy',  ru: 'Мест в классе',    en: 'Seats per class',  group: 'admissions' },
  { key: 'admissions.info2_value', uz: "18–22 ta o'rin",  ru: '18–22 места',      en: '18–22 seats',      group: 'admissions' },
  { key: 'admissions.info3_label', uz: 'Ish vaqti',       ru: 'Часы работы',      en: 'Working hours',    group: 'admissions' },
  { key: 'admissions.info3_value', uz: '09:00 dan 17:00 gacha', ru: 'С 09:00 до 17:00', en: '09:00 to 17:00', group: 'admissions' },
  { key: 'admissions.info4_label', uz: 'Grant imkoniyati', ru: 'Возможность гранта', en: 'Grant opportunity', group: 'admissions' },
  { key: 'admissions.info4_value', uz: 'Mavjud',          ru: 'Доступна',         en: 'Available',        group: 'admissions' },

  // Mashgulotlar page
  { key: 'mash.hero_eyebrow', uz: "Mashg'ulot va kurslar", ru: 'Занятия и курсы', en: 'Lessons & courses', group: 'mash' },
  { key: 'mash.hero_title',   uz: "Bola bizda nima o'rganadi", ru: 'Чему учится ваш ребёнок', en: 'What your child will learn', group: 'mash' },
  { key: 'mash.hero_lead',
    uz: "Bog'chadan 7-sinfgacha akademik fanlar, sport, ijod, AI va liderlik darslarini o'rganadi.",
    ru: 'От детского сада до 7 класса — академические предметы, спорт, творчество, ИИ и лидерство.',
    en: 'From preschool to grade 7 — academics, sports, creativity, AI and leadership.',
    group: 'mash',
  },
  { key: 'mash.grant_desc',
    uz: "Bola Seven School'da o'qish davomida akademik fanlar, sport, AI va liderlik darslarini birga o'rganadi.",
    ru: 'В Seven School ребёнок осваивает академические предметы, спорт, ИИ и лидерство вместе.',
    en: 'At Seven School your child learns academics, sport, AI and leadership together.',
    group: 'mash',
  },
  // Stages
  { key: 'mash.stages_eyebrow', uz: 'Bosqichlar',       ru: 'Этапы',        en: 'Stages',           group: 'mash' },
  { key: 'mash.stages_title',   uz: "Ta'lim bosqichlari", ru: 'Этапы обучения', en: 'Education stages', group: 'mash' },
  { key: 'mash.stg1_age',   uz: '4–6 yosh',  ru: '4–6 лет',  en: 'Ages 4–6',  group: 'mash' },
  { key: 'mash.stg1_title', uz: "Bog'cha",   ru: 'Детский сад', en: 'Pre-school', group: 'mash' },
  { key: 'mash.stg1_lead',
    uz: "Maktabga to'liq tayyorgarlik: o'qish, yozish, sanoq va ingliz tili. Har bir guruhda 18–22 bola, kun bo'yi ta'lim.",
    ru: 'Полная подготовка к школе: чтение, письмо, счёт и английский. По 18–22 ребёнка в группе, весь день.',
    en: 'Full school readiness: reading, writing, math and English. 18–22 kids per group, full day.',
    group: 'mash',
  },
  { key: 'mash.stg2_age',   uz: '1–7 sinf',  ru: '1–7 классы', en: 'Grades 1–7', group: 'mash' },
  { key: 'mash.stg2_title', uz: 'Maktab',    ru: 'Школа',     en: 'School',     group: 'mash' },
  { key: 'mash.stg2_lead',
    uz: 'Akademik fanlar, STEM, AI va liderlik darslari birgalikda. Kichik sinflar, 7-sinfgacha davom etadi.',
    ru: 'Академические предметы, STEM, ИИ и лидерство вместе. Малые классы — до 7 класса.',
    en: 'Academics, STEM, AI and leadership together. Small classes — through grade 7.',
    group: 'mash',
  },
  // Curriculum
  { key: 'mash.curr_eyebrow', uz: "O'quv dasturi",          ru: 'Учебная программа',    en: 'Curriculum',           group: 'mash' },
  { key: 'mash.curr_title',   uz: "Farzandingiz nima o'rganadi?", ru: 'Чему научится ваш ребёнок?', en: 'What will your child learn?', group: 'mash' },
  // Extra
  { key: 'mash.extra_eyebrow', uz: "Qo'shimcha",   ru: 'Дополнительно',    en: 'Beyond classes', group: 'mash' },
  { key: 'mash.extra_title',   uz: 'Darsdan tashqari', ru: 'Вне уроков',  en: 'Beyond the classroom', group: 'mash' },
  // Stages bullet lists (| separated)
  { key: 'mash.stg1_items',
    uz: 'Gimnastika va taekvondo|Mental arifmetika|Kulolchilik va rasm|Mutolaa darslari',
    ru: 'Гимнастика и тхэквондо|Ментальная арифметика|Гончарное дело и рисование|Уроки чтения',
    en: 'Gymnastics and taekwondo|Mental arithmetic|Pottery and drawing|Reading lessons',
    group: 'mash',
  },
  { key: 'mash.stg2_items',
    uz: 'Matematika, ingliz tili, fanlar|STEM amaliyot — Muhandis D|AI vositalar (5–7-sinf)|Tanqidiy fikrlash va liderlik',
    ru: 'Математика, английский, науки|STEM-практика — Muhandis D|ИИ-инструменты (5–7 классы)|Критическое мышление и лидерство',
    en: 'Math, English, sciences|STEM hands-on — Muhandis D|AI tools (grades 5–7)|Critical thinking and leadership',
    group: 'mash',
  },

  // Stages (home page) — for the timeline already in code
  { key: 'stages.eyebrow', uz: "Ta'lim bosqichlari", ru: 'Этапы обучения', en: 'Education stages', group: 'stages' },
  { key: 'stages.title',   uz: '4 yoshdan universitetgacha', ru: 'От 4 лет до университета', en: 'From age 4 to university', group: 'stages' },
  { key: 'stages.s1_age',   uz: '4–6 yosh',  ru: '4–6 лет',  en: 'Ages 4–6',  group: 'stages' },
  { key: 'stages.s1_title', uz: 'Pre-school', ru: 'Pre-school', en: 'Pre-school', group: 'stages' },
  { key: 'stages.s1_desc',  uz: "O'qish-yozish, mantiqiy fikrlash, ijtimoiy ko'nikmalar", ru: 'Чтение, письмо, логика, социальные навыки', en: 'Reading-writing, logical thinking, social skills', group: 'stages' },
  { key: 'stages.s2_age',   uz: '1–4 sinf',  ru: '1–4 классы', en: 'Grades 1–4', group: 'stages' },
  { key: 'stages.s2_title', uz: "Boshlang'ich", ru: 'Начальная школа', en: 'Primary', group: 'stages' },
  { key: 'stages.s2_desc',  uz: "Akademik baza, til o'rganish, 3 ta majburiy sport", ru: 'Академическая база, языки, 3 обязательных спорта', en: 'Academic base, languages, 3 mandatory sports', group: 'stages' },
  { key: 'stages.s3_age',   uz: '5–7 sinf',  ru: '5–7 классы', en: 'Grades 5–7', group: 'stages' },
  { key: 'stages.s3_title', uz: "O'rta",     ru: 'Средняя школа', en: 'Middle', group: 'stages' },
  { key: 'stages.s3_desc',  uz: 'STEM amaliyoti, AI, tanqidiy fikrlash va liderlik', ru: 'STEM, ИИ, критическое мышление и лидерство', en: 'STEM, AI, critical thinking and leadership', group: 'stages' },
  { key: 'stages.s4_age',   uz: '7-sinfdan keyin', ru: 'После 7 класса', en: 'After grade 7', group: 'stages' },
  { key: 'stages.s4_title', uz: 'Sodiq School', ru: 'Sodiq School', en: 'Sodiq School', group: 'stages' },
  { key: 'stages.s4_desc',  uz: 'Xalqaro universitetlarga tayyorgarlik', ru: 'Подготовка в международные университеты', en: 'Preparation for international universities', group: 'stages' },

  // Footer copyright
  { key: 'footer.copyright',
    uz: '© 2025 Seven School. Barcha huquqlar himoyalangan.',
    ru: '© 2025 Seven School. Все права защищены.',
    en: '© 2025 Seven School. All rights reserved.',
    group: 'footer',
  },

  // Aboutpage hero
  { key: 'about_page.hero_eyebrow', uz: 'Biz haqimizda', ru: 'О нас', en: 'About us', group: 'about_page' },
  { key: 'about_page.hero_title',
    uz: "Seven School — maktab haqida, jamoa va natijalar",
    ru: 'Seven School — о школе, команда и результаты',
    en: 'Seven School — about the school, team and results',
    group: 'about_page',
  },
  { key: 'about_page.hero_lead',
    uz: "2022-yilda Toshkentda o'zbek o'quvchilarini dunyoning eng TOP universitetlariga tayyorlash uchun ochilgan xususiy maktab.",
    ru: 'Частная школа, открытая в 2022 году в Ташкенте для подготовки узбекских учеников к поступлению в топ-университеты мира.',
    en: 'A private school opened in 2022 in Tashkent to prepare Uzbek students for the world\'s top universities.',
    group: 'about_page',
  },

  // Aloqa hero
  { key: 'aloqa.hero_eyebrow', uz: "Bog'lanish", ru: 'Связаться', en: 'Contact', group: 'aloqa' },
  { key: 'aloqa.hero_title',
    uz: "Biz bilan bog'laning",
    ru: 'Свяжитесь с нами',
    en: 'Get in touch',
    group: 'aloqa',
  },
  { key: 'aloqa.hero_lead',
    uz: 'Savollaringiz bormi yoki ariza topshirmoqchimisiz? Quyidagi formani to\'ldiring — biz 24 soat ichida javob beramiz.',
    ru: 'Есть вопросы или хотите подать заявку? Заполните форму — мы ответим в течение 24 часов.',
    en: 'Have questions or want to apply? Fill out the form — we will respond within 24 hours.',
    group: 'aloqa',
  },

  // Blog hero
  { key: 'blog.hero_eyebrow', uz: 'Blog', ru: 'Блог', en: 'Blog', group: 'blog' },
  { key: 'blog.hero_title',
    uz: 'Foydali maqolalar',
    ru: 'Полезные статьи',
    en: 'Useful articles',
    group: 'blog',
  },
  { key: 'blog.hero_lead',
    uz: "IELTS, SAT, AQSh va Yevropa universitetlari uchun ariza, motivatsion xat va o'qish bo'yicha amaliy qo'llanmalar.",
    ru: 'IELTS, SAT, заявки в университеты США и Европы, мотивационные письма и практические руководства.',
    en: 'IELTS, SAT, applications to US/European universities, motivation letters and practical study guides.',
    group: 'blog',
  },

  // Natijalar hero
  { key: 'natijalar.hero_eyebrow', uz: 'Bizning natijalar', ru: 'Наши результаты', en: 'Our results', group: 'natijalar' },
  { key: 'natijalar.hero_title',
    uz: "O'quvchilar natijalari",
    ru: 'Результаты учеников',
    en: 'Student results',
    group: 'natijalar',
  },
  { key: 'natijalar.hero_lead',
    uz: 'Talabalarimizning IELTS va SAT imtihonlarida erishgan natijalari va dunyoga ochilgan eshiklar.',
    ru: 'Результаты наших студентов на IELTS и SAT, и двери, открытые в мир.',
    en: 'Our students\' IELTS and SAT results, and doors opened to the world.',
    group: 'natijalar',
  },
];

export async function seedSettings() {
  console.log('[seed] settings...');
  for (const s of settings) {
    await query(
      `INSERT INTO settings (\`key\`, value_uz, value_ru, value_en, value_raw, \`group\`, description)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [s.key, s.uz ?? null, s.ru ?? null, s.en ?? null, s.raw ?? null, s.group ?? 'general', s.description ?? null],
    );
  }
}
